sudo: required
services:
    - docker

before_install:
    - docker build -t ammarkureja/test-suit-image -f Dockerfile.dev .

script: 
    - docker run -e CI=true ammarkureja/test-suit-image npm run test

deploy: 
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "continuous-integration-and-deployment-with-aws"
    env: "ContinuousIntegrationAndDeploymentWi-env"
    bucket_name: "elasticbeanstalk-us-east-1-017425166832"
    bucket_path: "continuous-integration-and-deployment-with-aws"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"